name: retrieve

on:
  discussion:
    types:
      - created
      - edited
      - deleted
  discussion_comment:
    types:
      - created
      - edited
      - deleted
  workflow_dispatch:

jobs:
  retrieve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: read
    if: ${{ github.event.discussion.category.name == 'Posts' && github.event.discussion.user.login == github.repository_owner }}
    steps:
      - uses: actions/checkout@v6
      - run: echo "${{ toJSON(github.event.discussion) }}"
        continue-on-error: true
      - run: echo "${{ github.event.discussion.title }}"
      - run: echo "${{ github.event.discussion.created_at }}"
      - run: echo "${{ github.event.discussion.updated_at }}"
      - run: echo "${{ github.event.discussion.comments }}"
      - run: echo "${{ github.event.discussion.body }}"
