name: retrieve

on:
  discussion:
    types:
      - created
      - edited
      - deleted
  discussion_comment:
    types:
      - created
      - edited
      - deleted
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      discussions: read
    if: ${{ github.event.discussion.category.name == 'Posts' && github.event.discussion.user.login == github.repository_owner }}
    steps:
      - name: Failed
        if: failure()
        run: exit 1

  discussion:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: read
    # if: ${{ !github.event.comment }}
    steps:
      - uses: actions/checkout@v6
      - run: echo "${{ toJSON(github.event.discussion) }}"
        continue-on-error: true
      - run: echo "${{ github.event.discussion.title }}"
      - run: echo "${{ github.event.discussion.created_at }}"
      - run: echo "${{ github.event.discussion.updated_at }}"
      - run: echo "${{ github.event.discussion.comments }}"
      - run: echo "${{ github.event.discussion.body }}"
      - name: Build markdown
        id: build_md
        run: |
          TITLE='${{ github.event.discussion.title }}'
          MD_CONTENT=$(cat <<EOF
          ---
          title: "${TITLE//\"/\\\"}"
          created_at: "${{ github.event.discussion.created_at }}"
          updated_at: "${{ github.event.discussion.updated_at }}"
          comments: ${{ github.event.discussion.comments }}
          ---

          ${{ github.event.discussion.body }}
          EOF
          )
          echo "$MD_CONTENT"
          echo "markdown<<EOF" >> $GITHUB_OUTPUT
          echo "$MD_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.build_md.outputs.markdown }}"

  discussion_comment:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: read
    if: ${{ github.event.comment }}
    steps:
      - uses: actions/checkout@v6
      - run: echo "${{ toJSON(github.event.comment) }}"
        continue-on-error: true
      - run: echo "${{ github.event.comment.created_at }}"
      - run: echo "${{ github.event.comment.updated_at }}"
      - run: echo "${{ github.event.comment.child_comment_count }}"
      - run: echo "${{ github.event.comment.body }}"
      - name: Build markdown
        id: build_md
        run: |
          TITLE='${{ github.event.discussion.title }}'
          MD_CONTENT=$(cat <<EOF
          ---
          title: "${TITLE//\"/\\\"}"
          created_at: "${{ github.event.comment.created_at }}"
          updated_at: "${{ github.event.comment.updated_at }}"
          comments: ${{ github.event.comment.child_comment_count }}
          ---

          ${{ github.event.comment.body }}
          EOF
          )
          echo "$MD_CONTENT"
          echo "markdown<<EOF" >> $GITHUB_OUTPUT
          echo "$MD_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.build_md.outputs.markdown }}"
