# https://tech.excite.co.jp/entry/2023/12/21/141427

name: Sync article

on:
  discussion:
    types:
      - created
      - edited
      - deleted
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      discussions: read
    steps:
      - run: ${{ github.event.discussion.category.name == 'Posts' && github.event.discussion.user.login == github.repository_owner }}

  discussion:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: read
    env:
      id: ${{ github.event.discussion.node_id }}
    steps:
      - name: Print full data
        run: echo "${{ toJSON(github.event.discussion) }}"
        continue-on-error: true

      - run: |
          pwd
          ls -lh
      - name: Build markdown
        run: |
          TITLE='${{ github.event.discussion.title }}'
          cat > "${{ env.id }}.md" <<EOF
          ---
          title: "${TITLE//\"/\\\"}"
          created_at: "${{ github.event.discussion.created_at }}"
          updated_at: "${{ github.event.discussion.updated_at }}"
          comments: ${{ github.event.discussion.comments }}
          ---

          ${{ github.event.discussion.body }}
          EOF
      - run: |
          ls -lh
          cat "${{ env.id }}.md" >> "$GITHUB_STEP_SUMMARY"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create data branch if missing and switch
        run: |
          if git ls-remote --heads origin data | grep -q data; then
            git fetch origin data:data
            git switch data
          else
            git switch -c data
          fi
      - name: Make changes and push
        run: |
          if ${{ github.event.action == 'created' || github.event.action == 'edited' }} then
            git add .
            git commit -m "add ${{ env.id }}.md" || echo "no changes"
          else
            git rm ${{ env.id }}.md
            git commit -m "delete ${{ env.id }}.md"
          fi
          git push -u origin data
